### PR TITLE
Fix build config

### PR DESCRIPTION
**Pull request by ofek**
## Motivation and Context

I stumbled upon it so thought I'd fix 🙂

### CODE REVIEW

**Comment by adam-hamsuth** [comment]
My first time creating a package thanks for the help.

Did you build hatchling??

**Comment by ofek** [comment]
I wrote it yes

**Comment by adam-hamsuth** [comment]
Thats really cool! I met a python legend today :)
 I do have to deny your pull request for compliance reasons even tho its only a few lines. I have implemented the changes however. Thanks for pointing them out and correcting them.

**Comment by ofek** [comment]
No worries, happy to help!

**Pull request closed without merging**
